name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for ASP.NET Web
      run: dotnet restore ./Path/To/Your/AspNetWebProject.csproj

    - name: Restore dependencies for WinForms App
      run: dotnet restore ./Path/To/Your/WinFormsAppProject.csproj

    - name: Build ASP.NET Web
      run: dotnet build ./Path/To/Your/AspNetWebProject.csproj --no-restore

    - name: Build WinForms App
      run: dotnet build ./Path/To/Your/WinFormsAppProject.csproj --no-restore

    - name: Test ASP.NET Web
      run: dotnet test ./Path/To/Your/AspNetWebProject.csproj --no-build --verbosity normal

    - name: Test WinForms App
      run: dotnet test ./Path/To/Your/WinFormsAppProject.csproj --no-build --verbosity normal
